### PR TITLE
ExtraTON DeBrowser Controller

### PR DESCRIPTION
**Pull request by qwertys318**

### CODE REVIEW

**Comment by Artem-Zhdanov** [comment]
Hi guys!  I wanted to push some changes, but could not, did you check the box "Allow edits from maintainers.” ?

**Comment by Artem-Zhdanov** [comment]
Never mind, I suggest changing only a couple of lines to unify with other tools:
 1. `tondev debrowser version`  - lists available versions in descending order.
 2. `tondev debrowser start ` - runs the latest version if no parameter is specified
  ```
 diff --git a/src/controllers/debrowser/command/start.ts b/src/controllers/debrowser/command/start.ts
index a66846f..63034b3 100644
--- a/src/controllers/debrowser/command/start.ts
+++ b/src/controllers/debrowser/command/start.ts
@@ -12,12 +12,13 @@ async function writeEnterMessage(docker: DevDocker, terminal: Terminal, containe
 
 export const startCommand: Command = {
     name: "start",
-    title: "Start ExtraTON DeBrowser",
+    title: "Start ExtraTON DeBrowser, default is 'latest'",
     args: [{
         isArg: true,
         name: 'version',
         type: 'string',
         title: 'ExtraTON DeBrowser version (semver compatible)',
+        defaultValue: 'latest',
     }],
     async run(terminal: Terminal, args: { version: string }): Promise<void> {
         await controlInstances(async (docker, def) => {
diff --git a/src/controllers/debrowser/installer.ts b/src/controllers/debrowser/installer.ts
index cc1f182..b15cecb 100644
--- a/src/controllers/debrowser/installer.ts
+++ b/src/controllers/debrowser/installer.ts
@@ -1,4 +1,4 @@
-import {compareVersions, httpsGetJson} from "../../core/utils";
+import {compareVersionsDescending, httpsGetJson} from "../../core/utils";
 import {ContainerDef, DevDocker} from "../../core/docker";
 import Dockerode from "dockerode";
 
@@ -7,7 +7,7 @@ const DOCKER_CONTAINER_NAME = "extraton-debrowser";
 
 export async function getAvailableVersions(): Promise<string[]> {
     const url = `https://registry.hub.docker.com/v2/repositories/${DOCKER_IMAGE_NAME}/tags/`;
-    return (await httpsGetJson(url)).results.map((x: any) => x.name).sort(compareVersions);
+    return (await httpsGetJson(url)).results.map((x: any) => x.name).sort(compareVersionsDescending);
 }
 
 function instanceContainerDef(version?: string): ContainerDef {
@@ -39,6 +39,7 @@ export async function controlInstances(
     control: (docker: DevDocker, def: ContainerDef) => Promise<void>,
     version?: string
 ): Promise<void> {
+    if (version === 'latest') version = (await getAvailableVersions())[0];
     const def: ContainerDef = instanceContainerDef(version);
     await control(new DevDocker(), def);
 }
```

**Comment by qwertys318** [comment]
- Suggestions have applied.
- Command "interfaces" has added.

**Comment by qwertys318** [comment]
1. All tags before 1.5.0 have removed.
2. Corrected: ba60b063737429b89d64a383a9643152c36af6e4

**Review by Artem-Zhdanov — APPROVED** [review]

**Pull request merged**
